### ISSUE TITLE
Runnig aTRAM with Transcript Input

### ISSUE THREAD

**Issue by erdikucuk** [juliema/aTRAM#164]
I am trying to run aTRAM with mRNA seq as bait on a C. elegans dataset. However, my success rate is so far is very low (less than 1 percent of the genes assembled with 20 iterations). I expected a higher success rate because aTRAM can work with protein sequences and theoretically mRNA seqs from the same species should work just fine. Is there anything in the aTRAM pipeline that makes it unsuitable for that kind of work?

**Comment by juliema** [comment]
A few quick questions, because it seems like this should work.  Do you have
an estimate of coverage?  If you have really low coverage I would use
velvet to do the assemblies as it works better.

Just checking a few things here:
1. Did you assemble the aTRAM library?
2. Did you turn on the protein flag?

One thing I might try is turning on the temp files just to make sure that
you are in fact getting blast hits.

example:

perl aTRAM.pl  -reads   atramlibrary -target target.fasta -templifes
tempfilename.out  -protein  -out outfilename

that will keep the files that generate the blast hits at each iteration so
you can see what it is finding.

Let me know how all of that goes.

Thanks!
Julie

**Comment by juliema** [comment]
Hi Erdi,  comments below

1) I have built an aTRAM library with format_sra.pl and it does seem to be
fine  -- ok great. have you been able to assemble other genes?

2) I haven't turn on the protein flag because my input consists of
nucleotide sequences. Will it still work?
right ok if you are starting from nucleotide then dont turn on the protein
flag.

3) One thing I want to ask is how many input seqs you usually process on a
single run. I have 1000 transcripts, should I split that into smaller bins?

I have each transcript as a separate flle and submit each job separately,
usually I submit 20 - 30 jobs at once depending on computational resources.

4) The coverage of the dataset is around 70x, I wil definetily try Velvet
as well.

Ok with this level of coverage you should be totally fine for trinity or
abyss.


I would start with a single locus turn on the temp files and let me know
what you get from that.

J

**Comment by juliema** [comment]
One other issue here is that if you can do protein sequences BLAST will do a tblastn search and this works better for more divergent sequences.

**Comment by juliema** [comment]
going to close this issue as we port to 2.0. If this issue still persists please create a new issue.
