### ISSUE TITLE
add single ends flag to preprocessor

### ISSUE THREAD

**Issue by juliema** [juliema/aTRAM#212]
allow user to specify if the dataset is from a single end run.

**Comment by rafelafrance** [comment]
So, we have a choice to make here. If some one selects --end-1 (or --end-2 or --single-ends) and the parser finds "/2" in the sequence name do we go with the "/2" or with the selected "/1"?

I suggest that we go with the command line option --end-1 and force it to "/1" because we also provide the --mixed-ends option. But you may have different opinions.

**Comment by juliema** [comment]
agreed. lets go with what they say for now and then if this seems to be  a big issue we can change later?
