### ISSUE TITLE
AssertionError in the tests of fill_blast_fasta()

### ISSUE THREAD

**Issue by nylander** [juliema/aTRAM#230]
Hi,

I'm installing aTRAM (master branch, 2018 Nov 02) on Ubuntu Linux 18.04, and are getting problems with the test suit:

When running `pytest test` (in virtualenv), I get an AssertionError triggered on line 210 in test_atram_preprocessor.py (in function test_create_one_blast_shard). Basically, the code is testing "if the args and keyword args passed in are different to the last call to the mock", and where there is an expected call compared to an actual call:
```
E           AssertionError: Expected call: fill_blast_fasta('blast_db_1', 'temp_dir_1/pytest_011.fasta', ['limit', 'offset'])
E           Actual call: fill_blast_fasta('blast_db_1', 'temp_dir_1/pyt_011.fasta', ['limit', 'offset'])
```
What differ are the file names (expected: "pytest_011.fasta" vs. actual "pyt_011.fasta").

**Changing the expected name in file test_atram_preprocessor.py (line 207) will make the test work**, but I do not (yet) know if, or how, this will affect the functionality of the software.

Any comments are most welcome.

Cheers
Johan

**Comment by rafelafrance** [comment]
Sorry for the slow reply.

FYI: This change is safe but we can do better. I was being lazy and chopping off 3 characters from the file name because I was always expecting a ".py"  extension which doesn't happen for pytest.  A more robust solution would be to use `os.path.splitext()`.

I am made the change and thank you for your help.
