### ISSUE TITLE
Possible v 2.1.2 bug: idle forever at locus with huge amount of blast hits

### ISSUE THREAD

**Issue by HeatherKates** [juliema/aTRAM#260]
Hi Julie and Rafe,
Was anything changed in the new version to address the issue of atram getting stuck (due to time or memory) when assembling a locus with a huge amount of blast hits? We had talked about it a while back and I'd had success using the evalue option for blast, but so far it looks like the problem is back now even with the evalue set at what had been working before to limit the number of blast hits. I'll keep looking at our data to see if something is different, but in case this rings a bell the log file is attached. Thank you!
[atram.39898456.txt](https://github.com/juliema/aTRAM/files/3541918/atram.39898456.txt)

**Comment by juliema** [comment]
I think atram has a timeout option built in so it should go automatically to the next locus if one gets slow.

can you send us some data to test this?

atram library - or fastq files and the reference?

In fact a few references -- some that go fast and some that go slow?

thanks,

Julie


On Mon, Aug 26, 2019 at 9:02 AM Heather Kates <notifications@github.com<mailto:notifications@github.com>> wrote:

Hi Julie and Rafe,
In the previous version we'd talked about the problem of memory use when assembling a locus with a huge amount of blast hits. When atram is run through a slurm scheduler and especially in a batch across many libaries (as all our atram use is), this is a big problem because jobs are killed left and right due to out of memory at that locus. Was a change made to get around this problem in the new version? I ask because with the new version I'm seeing a different version of the problem- at this problem locus atram is idle until the job runs out of time. So it kind of looks like the problem of the job requesting too much memory was solved, but not to the extent that it actually moves forward to the next locus. For example, atram assembled 70 loci in 2 hours and then spent hours 3-24 at locus 71 (time limit was 24 hours) without writing any files. Log file is attached. Thank you!
atram.39898456.txt<https://github.com/juliema/aTRAM/files/3541918/atram.39898456.txt>

**Comment by HeatherKates** [comment]
Here are the raw read files https://drive.google.com/drive/folders/1eiBFD_iqCE1xH3Q-MdN-E4hYad34PxsE?usp=sharing
WF07 gets stuck at Locus_071, WF08 and WA08 do not.

One thing I noticed when copying these files is that the preprocessing step was done with v 2.0. That doesn't seem related to anything, but could it be problematic?

Thanks!
Heather Rose


Postdoctoral Associate

Florida Museum of Natural History

Dickinson Hall

1659 Museum Road

(215) 588-8694


________________________________

**Comment by rafelafrance** [comment]
aTRAM will error out if the preprocessor version is incompatible, so it's something else. The timeout option may have a bug? I'll have a look on Friday.

**Comment by juliema** [comment]
thanks Rafe!

On Tue, Aug 27, 2019 at 10:55 AM rafe <notifications@github.com<mailto:notifications@github.com>> wrote:

aTRAM will error out if the preprocessor version is incompatible, so it's something else. The timeout option may have a bug? I'll have a look on Friday.

**Comment by rafelafrance** [comment]
@Heather
Did the hang happen during the Blast step or during the assembly? I don't have any timeouts on blastn or tblastn, and that could definitely hang things.

@Julie
If it's hanging on blast, would 5 minutes a reasonable default for a timeout there?

@Heather & @Julie
I just tested the timeout option by setting --timeout=0. The assembler fails with the appropriate error while assembling.

**Comment by juliema** [comment]
@Kates,Heather R<mailto:hkates@ufl.edu>  could you send the log file so we can see where it hangs?

@Lafrance,Raphael<mailto:rlafrance@flmnh.ufl.edu> lets do 10 min in case someone has a huge library.



On Fri, Sep 6, 2019 at 8:51 AM rafe <notifications@github.com<mailto:notifications@github.com>> wrote:

@Heather<https://github.com/Heather>
Did the hang happen during the Blast step or during the assembly? I don't have any timeouts on blastn or tblastn, and that could definitely hang things.

@julie<https://github.com/julie>
If it's hanging on blast, would 5 minutes a reasonable default for a timeout there?

@Heather<https://github.com/Heather> & @julie<https://github.com/julie>
I just tested the timeout option by setting --timeout=0. The assembler fails with the appropriate error while assembling.

**Comment by juliema** [comment]
Hey @HeatherKates one of the other ways we have fixed this is to set the maximum number of blast hits allowed.   using the --max-target-seqs . -- this number will be the maximum seqs blast will find per shard. So if you have 2 shards and you set max target seqs to 500 you will get noo more than 1,000 hits.

will you try first without that option to see if it is resolved then add this option to resolve it for your dataset?
