### ISSUE TITLE
atram.py, nothing is assembling. spades error

### ISSUE THREAD

**Issue by HeatherKates** [juliema/aTRAM#271]
Running atram.py for the first time in a long time, and nothing is assembling. I've tried it on samples/loci that have definitely assembled before, with the same files. The blast search will return a ton of hits, but then I get the error:
The assembler failed with error: Command 'spades.py  --only-assembler --threads 1 --memory 49 --cov-cutoff off -o Temp/atram_9u35uxhv/P051_WA01_candidate_gene_proteins_short_names_Medtr1g006690_1_1.fasta_01_s9b5s0_5/spades' returned no
n-zero exit status 1.

The full output and example input files and full output with error are here: https://drive.google.com/drive/folders/1sc2nP8_KgNGHgtSLFJ5EaEGXFerwNCe0

Here is the run command: atram.py -b P051_WA01 --cpus 1 -p -Q /ufrc/soltis/hkates/NITFIX/Reference_sequences/candidate_gene_proteins_short_names.fasta -i 5 -a spades -o Assemblies_Functional/ --log-file Test.log --temp-dir Temp/ --keep-temp-dir

**Comment by rafelafrance** [comment]
Excellent test case! It's small and, hopefully, repeatable. Thanks.

However, there are some minor issues with the files:
- P051_WA01.zip appears to be an empty zip file
- I also need P051_WA01.atram.log

**Comment by rafelafrance** [comment]
I could not run your example because of some missing files. Here's the status for the assemblers:
- velvet: ok
- trinity: ok
- abyss: ok
- spades: (of course) errors with the default linux install. I had to install the newer `SPAdes-3.13.2-Linux` for it to work.

So, on my test data for ptgor, Only the new version of spades is working. I'm not sure if this is the same issue for you because I still need to look at `P051_WA01.atram.log`.


FYI: Here's the command I ran `./atram.py @args/ptgor_spades.args`

And a little more helpful, here are the contents of the ptgor_spades.args file

```
--query-split=query/all_Phum.fasta
--blast-db=db/ptgor
--output-prefix=output/spades
--log-file=output/ptgor_atram.log
--assembler=spades
--temp-dir=temp
--keep-temp-dir
--path=/home/rafe/bin/SPAdes-3.13.2-Linux/bin
```

**Comment by HeatherKates** [comment]
Rafe, well this introduced a weird question for me- all my P051_WA01.zip directories output by preprocessor are empty (thousands of them). What are they supposed to have in them? I never looked in them, the assembly has always worked fine though so I don't think that's the problem.

For now, I'm just using the older version v 2.1.2 atram (and it's working) I guess it's a compatibility issue with spades and atram v 2.3, I can't get spades updated on hipergator until next week. I will let you know if that fixes it. Thanks.
